repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
        -   id: check-toml
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-builtin-literals
  -   repo: https://github.com/doublify/pre-commit-rust
      rev: master
      hooks:
        -   id: fmt
  -   repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.11.13
      hooks:
        -   id: ruff-format
        -   id: ruff-check
