from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from types import ModuleType

_modules: dict[str, ModuleType]

def load_preset_plugins() -> None: ...
def load_plugin(plugin: str) -> None: ...
def unload_plugin(plugin: str) -> None: ...
def reload_plugin(plugin: str) -> None: ...
