from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from shinqlx import AbstractChannel, AbstractDummyPlayer

class RconDummyPlayer(AbstractDummyPlayer):
    def __init__(self) -> None: ...
    @property
    def steam_id(self) -> int: ...
    @property
    def channel(self) -> AbstractChannel: ...
    def tell(self, msg: str, **kwargs: str) -> None: ...
