name: miri

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Install Rust nightly toolchain
      run:
        rustup update nightly
    - name: Install Miri
      run: |
        rustup toolchain install nightly --component miri
        rustup override set nightly
        cargo miri setup
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Test with miri
      run: cargo +nightly miri test
